name: CodeGuru Security Example
on:
  pull_request:
    branches:
      - 'master'

permissions:
  id-token: write
  # for writing security events.
  security-events: write
  # only required for workflows in private repositories
  actions: read
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Respository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Find changed lines
        id: changed_lines
        uses: hestonhoffman/changed-lines@v1
        
      - name: Print changed lines
        run: echo ${{ steps.changed_lines.outputs.changed_lines }}

      - name: Get Git diff
        id: get_git_diff
        run: |
          mkdir qsa-diff-folder
          git diff origin/${GITHUB_BASE_REF} origin/${GITHUB_HEAD_REF} > qsa-diff-folder/qsa-git-diff.diff

      - name: Print diff
        run: cat qsa-diff-folder/qsa-git-diff.diff

      - name: Print root content
        run: |
          echo "Root content"
          ls -la
          echo ".git content"
          ls -la .git

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::336595444142:role/CodeGuruSecurityGitHubAccessRole
          aws-region: us-east-1
          role-session-name: GitHubActionScript

      - name: CodeGuru Security
        uses: aws-actions/codeguru-security@v1
        with:
          source_path: .
          aws_region: us-east-1
          fail_on_severity: Critical
      
      - name: Print findings
        run: |
          ls -l
          cat codeguru-security-results.sarif.json

      # If you want content in security scanning, you’ll need to enable codescanning by going into github.
      # https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning-for-a-repository
      - name: Upload result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeguru-security-results.sarif.json
